apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-deployment
  labels:
    app: randomservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: randomservice
  template:
    metadata:
      labels:
        app: randomservice
    spec:
      containers:
      - name: randomservice
        image: klyse/randomservice:1.0.0
        ports:
        - containerPort: 3000
